require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EntityKeysController do

  def mock_entity_key(stubs={})
    @mock_entity_key ||= mock_model(EntityKey, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all entity_keys as @entity_keys" do
      EntityKey.stub(:all) { [mock_entity_key] }
      get :index
      assigns(:entity_keys).should eq([mock_entity_key])
    end
  end

  describe "GET show" do
    it "assigns the requested entity_key as @entity_key" do
      EntityKey.stub(:find).with("37") { mock_entity_key }
      get :show, :id => "37"
      assigns(:entity_key).should be(mock_entity_key)
    end
  end

  describe "GET new" do
    it "assigns a new entity_key as @entity_key" do
      EntityKey.stub(:new) { mock_entity_key }
      get :new
      assigns(:entity_key).should be(mock_entity_key)
    end
  end

  describe "GET edit" do
    it "assigns the requested entity_key as @entity_key" do
      EntityKey.stub(:find).with("37") { mock_entity_key }
      get :edit, :id => "37"
      assigns(:entity_key).should be(mock_entity_key)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created entity_key as @entity_key" do
        EntityKey.stub(:new).with({'these' => 'params'}) { mock_entity_key(:save => true) }
        post :create, :entity_key => {'these' => 'params'}
        assigns(:entity_key).should be(mock_entity_key)
      end

      it "redirects to the created entity_key" do
        EntityKey.stub(:new) { mock_entity_key(:save => true) }
        post :create, :entity_key => {}
        response.should redirect_to(entity_key_url(mock_entity_key))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entity_key as @entity_key" do
        EntityKey.stub(:new).with({'these' => 'params'}) { mock_entity_key(:save => false) }
        post :create, :entity_key => {'these' => 'params'}
        assigns(:entity_key).should be(mock_entity_key)
      end

      it "re-renders the 'new' template" do
        EntityKey.stub(:new) { mock_entity_key(:save => false) }
        post :create, :entity_key => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entity_key" do
        EntityKey.stub(:find).with("37") { mock_entity_key }
        mock_entity_key.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :entity_key => {'these' => 'params'}
      end

      it "assigns the requested entity_key as @entity_key" do
        EntityKey.stub(:find) { mock_entity_key(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:entity_key).should be(mock_entity_key)
      end

      it "redirects to the entity_key" do
        EntityKey.stub(:find) { mock_entity_key(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(entity_key_url(mock_entity_key))
      end
    end

    describe "with invalid params" do
      it "assigns the entity_key as @entity_key" do
        EntityKey.stub(:find) { mock_entity_key(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:entity_key).should be(mock_entity_key)
      end

      it "re-renders the 'edit' template" do
        EntityKey.stub(:find) { mock_entity_key(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entity_key" do
      EntityKey.stub(:find).with("37") { mock_entity_key }
      mock_entity_key.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the entity_keys list" do
      EntityKey.stub(:find) { mock_entity_key }
      delete :destroy, :id => "1"
      response.should redirect_to(entity_keys_url)
    end
  end

end
